### PR TITLE
3.1.7

### PR DESCRIPTION
**Pull request by JerrySmidt**
* Add autocomplete field bypass link (optional, disabled by default).
* New admin interface.

### CODE REVIEW

**Comment by JelleGe** [comment]
Good solution! Maybe a good idea to wrap the autocomplete bypass link into the same div as the autofill output, to display it as valid and invalid.

**Comment by JelleGe** [comment]
@JerrySmidt Great new feature! Sadly it does not work for the Billing Address in the checkout. Maybe a good addition?

**Comment by JerrySmidt** [comment]
Thanks for the feedback @JelleGe. The bypass feature is now also included in the billing form.

**Comment by JelleGe** [comment]
Thanks @JerrySmidt! Also saw my issue #55? Because this also exist in the new version.

**Pull request merged**
